### ISSUE TITLE
No permite insertar datos a la base de datos

### ISSUE THREAD

**Issue by AndresCGO** [jdrodas/SiembrasCorantioquia#2]

**Comment by jdrodas** [comment]
Entendido!

Procedo con la implentación!

**Comment by jdrodas** [comment]
Hola @AndresCGO, gracias por el issue!

Como demostración, implementamos la funcionalidad de inserción de nueva siembra, con un formulario independiente:

![image](https://user-images.githubusercontent.com/29258977/193492288-796d21a9-f3b0-4c09-a060-16636f6c9c0f.png)

La inserción para el resto de las entidades se realizará de la misma manera.
