### ISSUE TITLE
UI mejorable

### ISSUE THREAD

**Issue by GabrielCornejoB** [jdrodas/SiembrasCorantioquia#4]
Esa interfaz está criminal, aquí en Pinterest puede tomar referencias: https://co.pinterest.com/search/pins/?q=crud%20ui&rs=typed

**Comment by jdrodas** [comment]
Gracias @GabrielCornejoB por la recomendación.

Entendiendo que la prioridad del proyecto es demostrar conectividad a la base de datos, la UI no debería estar tan abandonada como para distraer de la utilización.

Se implementó el nuevo diseño que trata de modernizar un poco la presentación, pero sin perder desviarnos del objetivo principal.

![image](https://user-images.githubusercontent.com/29258977/193475651-b2aae21b-6920-484d-a51b-432a193367b6.png)
