### ISSUE TITLE
Verificar el funcionamiento de las excepciones

### ISSUE THREAD

**Issue by dahumoru** [jdrodas/SiembrasCorantioquia#5]

**Comment by jdrodas** [comment]
Gracias @dahumoru por el issue.

Efectivamente estamos controlando algunas excepciones, pero deberíamos ser más rigurosos con el tratamiento del mensaje,

Se actualizarán todos los métodos CRUD de Acceso a datos para que puedan subir a la UI el mensaje de error específico de la excepción.

**Comment by jdrodas** [comment]
Hola!

Algunas referencias a los cambios implementados y que se realizarán en el resto de las operaciones CRUD que generen excepciones:

A nivel de la forma, cuando se llame el método, ahora recibimos el mensaje de error de la excepción:

![image](https://user-images.githubusercontent.com/29258977/193477071-aaecf9a7-7c57-42e4-b079-e01af4acb877.png)

Cambiamos la definición del método asi:

![image](https://user-images.githubusercontent.com/29258977/193477156-920ee2e1-5ac4-4c96-b395-38b1ef7402a9.png)

Cuando se presenta la excepción, enviamos el mensaje de error:

![image](https://user-images.githubusercontent.com/29258977/193477204-25aa3904-982c-4f11-9ab6-5417c2e95187.png)
