### ISSUE TITLE
Los eventos de todos los formularios estan sin documentar

### ISSUE THREAD

**Issue by AndresCGO** [jdrodas/SiembrasCorantioquia#6]

**Comment by jdrodas** [comment]
Gracias @AndresCGO !

Se documentarán solo los métodos específicos construidos para soportar la funcionalidad de cada formulario.

Los eventos asociados a los controles son "auto-explicativos" en su nomenclatura, por lo que no requieren documentación adicional.

Se implementará inicialmente en los formularios CRUD de las siembras y progresivamente se implementará en los nuevos formularios.
