### ISSUE TITLE
No actualiza la tabla después de eliminar

### ISSUE THREAD

**Issue by GabrielCornejoB** [jdrodas/SiembrasCorantioquia#8]
Después de eliminar un registro de siembras, no se ve actualizada la tabla, toca cerrarla y abrirla para que se vea la tabla actualizada

**Comment by jdrodas** [comment]
Gracias @GabrielCornejoB !

En todas las formas donde se afectan siembras (inserción, actualización, borrado) se colocó un método llamado RefrescaFormasSiembras() el cual valida si la forma de reportes está abierta y refresca la tabla que se visualiza en el datagridview.

![image](https://user-images.githubusercontent.com/29258977/195462744-79a34377-29ea-4040-8bd2-234450aace74.png)
